name: Deploy Node-RED Flow

on:
  push:
    branches:
      - main   # chỉ chạy khi có code mới push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to staging with scp
        run: |
          scp -o StrictHostKeyChecking=no flows.json settings.js \
          user@staging-server:/home/user/.node-red